### ISSUE TITLE
Update all languages to use newest CI code

### ISSUE THREAD

**Issue by snomos** [divvun/meta-pahkat-repo#2]
Now many languages have old CI & CD scripts/calls, and never end up in the nightly channel of Divvun Manager 2. Cf Meänkieli/Tornedalen Finnish and others in the screen shot below, with the latest nightly from June despite newer commits:

![](https://user-images.githubusercontent.com/1255285/99943097-6e509680-2d79-11eb-842a-42e71045dcdf.png)

**Comment by bbqsrc** [comment]
Take a copy of https://github.com/giellalt/lang-nno/blob/develop/.github/workflows/spellers.yml and put it in all the repos that you need it.

**Comment by snomos** [comment]
> Take a copy of https://github.com/giellalt/lang-nno/blob/develop/.github/workflows/spellers.yml and put it in all the repos that you need it.

Done, and is working, all spellers listed are now from today.

There is another bug that prevents Windows spellers from being properly built, I will keep this issue open until that bug is fixed. The core of it: `manifest.toml.in` files must be updated to have proper product codes, and with old codes stored in a legacy list. I am working my way through all languages.

**Comment by snomos** [comment]
All manifest files are now correct. Remaining build errors are either linguistic/actual *build* errors, or caused by missing pahkat entries, which is another thing. Closing this issue.
